# -*- coding: utf-8 -*-
"""Ujian akhir semeste.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u1mz8nEcVwBAR--KfXobV6KHSp7H5SzV
"""
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
from wordcloud import WordCloud

# 1. PENGATURAN PATH FILE
# Nama file harus sama persis dengan yang ada di GitHub
file_path = 'career_dataset_large.xlsx'

# 2. FUNGSI LOAD DATA DENGAN CACHE
@st.cache_data
def load_data():
    try:
        # Menambahkan engine='openpyxl' sangat penting untuk file .xlsx
        df = pd.read_excel(file_path, engine='openpyxl')
        return df
    except Exception as e:
        st.error(f"Error: Tidak dapat menemukan file '{file_path}'. Pastikan file sudah di-upload ke GitHub.")
        return None
# 2. PEMBERSIHAN DATA
# Menghapus spasi yang tidak terlihat agar tidak ada duplikat nama
df['Education Level'] = df['Education Level'].str.strip()

# 3. FILTER & MENGURUTKAN
# Menentukan 5 kategori utama yang diinginkan
target_levels = ["Intermediate", "Master's", "Bachelor's", "Matric", "PhD"]

# Memastikan data hanya berisi 5 level tersebut
df_filtered = df[df['Education Level'].isin(target_levels)].copy()

# 4. MEMBUAT TABEL RINGKASAN (Bukan Visual Grafik)
# Menghitung jumlah data per jenjang untuk memastikan semuanya muncul
summary_table = df_filtered['Education Level'].value_counts().reindex(target_levels).reset_index()
summary_table.columns = ['Education Level', 'Total Data']

# 5. MENAMPILKAN HASIL
print("Tabel Jenjang Pendidikan (Sesuai Filter):")
st.dataframe(summary_table)

print("\nContoh Data Mentah Setelah Filter:")
display(df_filtered.head(20))

# Kolom yang ingin dianalisis
cols = ['Specialization', 'Skills', 'Certifications', 'CGPA/Percentage', 'Recommended Career']
target_levels = ["Intermediate", "Master's", "Bachelor's", "Matric", "PhD"]

results = []

for level in target_levels:
    level_df = df[df['Education Level'] == level]

    for col in cols:
        counts = level_df[col].value_counts()
        if not counts.empty:
            results.append({
                'Jenjang': level,
                'Kolom': col,
                'Jumlah Unik (Beda)': level_df[col].nunique(),
                'Nilai Terpopuler': counts.index[0],
                'Frekuensi (Sama)': counts.iloc[0]
            })

# Menampilkan hasil dalam bentuk tabel
summary_df = pd.DataFrame(results)
display(summary_df)

# 2. PEMBERSIHAN & PEMBUATAN KOLOM (Penting agar tidak KeyError)
df['Education Level'] = df['Education Level'].str.strip()
# Membuat kolom Status_Keberhasilan (Ini yang tadi menyebabkan error karena belum ada)
df['Status_Keberhasilan'] = np.where(df['CGPA/Percentage'] >= 80, 'Berhasil', 'Gagal')

# 3. FUNGSI UNTUK MENGAMBIL SEMUA SKILL
def get_all_skills(subset):
    all_s = []
    for s in subset.dropna():
        # Memisahkan skill yang digabung dengan koma
        all_s.extend([i.strip() for i in str(s).split(',')])
    return pd.Series(all_s).value_counts()

# 4. MENGHITUNG SKILL PER KELOMPOK
# Sekarang kolom 'Status_Keberhasilan' sudah pasti ada
skill_berhasil = get_all_skills(df[df['Status_Keberhasilan'] == 'Berhasil']['Skills'])
skill_gagal = get_all_skills(df[df['Status_Keberhasilan'] == 'Gagal']['Skills'])

# 5. MENGHITUNG SELISIH (Skill Pembeda)
# Menghitung mana skill yang sering muncul di kelompok Berhasil tapi jarang di Gagal
diff_skill = (skill_berhasil - skill_gagal).sort_values(ascending=False).head(10)

# 6. VISUALISASI
plt.figure(figsize=(12, 7))
diff_skill.plot(kind='barh', color='seagreen')
plt.title('Top 10 Skill Pembeda (Lebih Sering Muncul di Kelompok Berhasil)', fontsize=14, fontweight='bold')
plt.xlabel('Selisih Frekuensi (Berhasil - Gagal)')
plt.ylabel('Nama Skill')
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.gca().invert_yaxis() # Agar yang tertinggi ada di atas
st.pyplot(fig)

plt.figure(figsize=(15, 7))
sns.boxplot(data=df, x='Recommended Career', y='CGPA/Percentage', palette='Set3')
plt.title('Sebaran CGPA Berdasarkan Rekomendasi Karier', fontsize=15, fontweight='bold')
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.7)
st.pyplot(fig)

# Membuat tabel silang (Crosstab)
plt.figure(figsize=(14, 8))
ct = pd.crosstab(df['Specialization'], df['Recommended Career'])

# Visualisasi dengan Heatmap
sns.heatmap(ct, annot=True, cmap='YlGnBu', fmt='d', cbar=True)
plt.title('Heatmap: Korelasi Spesialisasi vs Rekomendasi Karier', fontsize=15, fontweight='bold')
plt.xlabel('Rekomendasi Karier')
plt.ylabel('Spesialisasi')
st.pyplot(fig)

# Membuat Stacked Bar Chart
plt.figure(figsize=(15, 8))
career_dist = pd.crosstab(df['Education Level'], df['Recommended Career'], normalize='index') * 100

career_dist.plot(kind='bar', stacked=True, figsize=(15, 8), colormap='tab20')
plt.title('Distribusi Jenis Karier Berdasarkan Jenjang Pendidikan (%)', fontsize=15, fontweight='bold')
plt.ylabel('Persentase (%)')
plt.xlabel('Jenjang Pendidikan')
plt.legend(title='Karier', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.xticks(rotation=0)
st.pyplot(fig)

# 2. PENGOLAHAN DATA
# Membersihkan spasi pada Education Level agar tidak ada duplikat
df['Education Level'] = df['Education Level'].str.strip()

# Definisi Berhasil jika CGPA >= 80
df['Status_Keberhasilan'] = np.where(df['CGPA/Percentage'] >= 80, 'Berhasil', 'Gagal')

# Mengisi nilai yang kosong agar tidak error saat pemrosesan
df['Certifications'] = df['Certifications'].fillna('None')
df['Specialization'] = df['Specialization'].fillna('None')
df['Skills'] = df['Skills'].fillna('None')

# 3. FUNGSI UNTUK MENGHITUNG TOP ITEMS (Specialization, Skills, Certifications)
def get_top_items(dataframe, edu_level, status, column, top_n=5):
    # Filter berdasarkan jenjang pendidikan dan status keberhasilan
    subset = dataframe[(dataframe['Education Level'] == edu_level) &
                       (dataframe['Status_Keberhasilan'] == status)][column].dropna()

    all_items = []
    for entry in subset:
        # Pisahkan string jika berisi koma (terutama untuk Skills & Certifications)
        items = [item.strip() for item in str(entry).split(',')]
        all_items.extend(items)

    counts = Counter(all_items).most_common(top_n)
    if not counts:
        return pd.DataFrame(columns=['Item', 'Count'])
    return pd.DataFrame(counts, columns=['Item', 'Count'])

# 4. VISUALISASI UNTUK 5 JENJANG PENDIDIKAN
list_jenjang = ["Intermediate", "Master's", "Bachelor's", "Matric", "PhD"]

for jenjang in list_jenjang:
    if jenjang in df['Education Level'].unique():
        # Membuat figure dengan 4 baris (Spec, Skills, Certs, CGPA) x 2 kolom (Berhasil vs Gagal)
        fig, axes = plt.subplots(4, 2, figsize=(16, 24))
        fig.suptitle(f'Analisis Profil Lengkap: {jenjang} (Berhasil vs Gagal)',
                     fontsize=22, fontweight='bold', y=1.01)

        # -- BARIS 1: Specialization (Berhasil vs Gagal) --
        d_sp_b = get_top_items(df, jenjang, 'Berhasil', 'Specialization')
        if not d_sp_b.empty: sns.barplot(data=d_sp_b, x='Count', y='Item', ax=axes[0, 0], palette='Greens_r')
        axes[0, 0].set_title(f'Top Specialization ({jenjang} - Berhasil)')

        d_sp_g = get_top_items(df, jenjang, 'Gagal', 'Specialization')
        if not d_sp_g.empty: sns.barplot(data=d_sp_g, x='Count', y='Item', ax=axes[0, 1], palette='Reds_r')
        axes[0, 1].set_title(f'Top Specialization ({jenjang} - Gagal)')

        # -- BARIS 2: Skills (Berhasil vs Gagal) --
        d_s_b = get_top_items(df, jenjang, 'Berhasil', 'Skills')
        if not d_s_b.empty: sns.barplot(data=d_s_b, x='Count', y='Item', ax=axes[1, 0], palette='Greens_r')
        axes[1, 0].set_title(f'Top Skills ({jenjang} - Berhasil)')

        d_s_g = get_top_items(df, jenjang, 'Gagal', 'Skills')
        if not d_s_g.empty: sns.barplot(data=d_s_g, x='Count', y='Item', ax=axes[1, 1], palette='Reds_r')
        axes[1, 1].set_title(f'Top Skills ({jenjang} - Gagal)')

        # -- BARIS 3: Certifications (Berhasil vs Gagal) --
        d_c_b = get_top_items(df, jenjang, 'Berhasil', 'Certifications')
        if not d_c_b.empty: sns.barplot(data=d_c_b, x='Count', y='Item', ax=axes[2, 0], palette='Greens_r')
        axes[2, 0].set_title(f'Top Certifications ({jenjang} - Berhasil)')

        d_c_g = get_top_items(df, jenjang, 'Gagal', 'Certifications')
        if not d_c_g.empty: sns.barplot(data=d_c_g, x='Count', y='Item', ax=axes[2, 1], palette='Reds_r')
        axes[2, 1].set_title(f'Top Certifications ({jenjang} - Gagal)')

        # -- BARIS 4: Distribusi CGPA/Percentage --
        sub_b = df[(df['Education Level'] == jenjang) & (df['Status_Keberhasilan'] == 'Berhasil')]
        sns.histplot(sub_b['CGPA/Percentage'], ax=axes[3, 0], color='green', kde=True)
        axes[3, 0].set_title(f'Distribusi CGPA ({jenjang} - Berhasil)')

        sub_g = df[(df['Education Level'] == jenjang) & (df['Status_Keberhasilan'] == 'Gagal')]
        sns.histplot(sub_g['CGPA/Percentage'], ax=axes[3, 1], color='red', kde=True)
        axes[3, 1].set_title(f'Distribusi CGPA ({jenjang} - Gagal)')

        plt.tight_layout()
        st.pyplot(fig)
        print("\n" + "="*100 + "\n")
    else:
        print(f"Peringatan: Level {jenjang} tidak ditemukan dalam data.")

# 2. PEMBERSIHAN & FILTER DATA
# Menghapus spasi agar tidak ada duplikat nama (seperti Bachelor's ganda)
df['Education Level'] = df['Education Level'].str.strip()

# Menentukan 5 kategori target
target_levels = ["Intermediate", "Master's", "Bachelor's", "Matric", "PhD"]
df = df[df['Education Level'].isin(target_levels)].copy()

# 3. LOGIKA KEBERHASILAN
# Berhasil jika CGPA >= 80, selain itu Gagal
df['Status_Keberhasilan'] = np.where(df['CGPA/Percentage'] >= 80, 'Berhasil', 'Gagal')

# 4. PERHITUNGAN PERSENTASE
# A. Persentase Distribusi Keseluruhan (untuk Pie Chart)
dist_counts = df['Education Level'].value_counts(normalize=True) * 100
dist_df = dist_counts.reindex(target_levels).reset_index()
dist_df.columns = ['Education Level', 'Percentage']

# B. Persentase Berhasil vs Gagal per Jenjang (untuk Stacked Bar)
success_counts = df.groupby(['Education Level', 'Status_Keberhasilan'], observed=True).size().unstack(fill_value=0)
success_pct = success_counts.div(success_counts.sum(axis=1), axis=0) * 100
success_pct = success_pct.reindex(target_levels)

# 5. VISUALISASI
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(20, 8))

# --- Plot 1: Pie Chart (Distribusi Data) ---
colors = sns.color_palette('pastel')[0:5]
ax1.pie(dist_df['Percentage'], labels=dist_df['Education Level'], autopct='%1.1f%%',
        startangle=140, colors=colors, explode=[0.05]*5)
ax1.set_title('Proporsi Data per Jenjang Pendidikan', fontsize=15, fontweight='bold')

# --- Plot 2: Stacked Bar Chart (Persentase Berhasil vs Gagal) ---
success_pct.plot(kind='bar', stacked=True, ax=ax2, color=['#2ca02c', '#d62728'])
ax2.set_title('Persentase Berhasil vs Gagal per Jenjang', fontsize=15, fontweight='bold')
ax2.set_ylabel('Persentase (%)')
ax2.set_xlabel('Jenjang Pendidikan')
ax2.legend(title='Status', loc='upper right', bbox_to_anchor=(1.15, 1))

# Menambahkan label teks persentase di dalam bar
for p in ax2.patches:
    width, height = p.get_width(), p.get_height()
    x, y = p.get_xy()
    if height > 0:
        ax2.text(x + width/2,
                y + height/2,
                f'{height:.1f}%',
                horizontalalignment='center',
                verticalalignment='center',
                color='white',
                fontweight='bold',
                fontsize=11)

plt.tight_layout()
st.pyplot(fig)

# Menampilkan tabel hasil perhitungan di konsol
print("\n--- RINGKASAN PERSENTASE KEBERHASILAN ---")
print(success_pct)

# Menggabungkan semua teks di kolom Skills menjadi satu string besar
all_skills = " ".join(df['Skills'].dropna().astype(str))

# Membuat WordCloud
wordcloud = WordCloud(width=800, height=400, background_color='white',
                      colormap='viridis', max_words=50).generate(all_skills)

plt.figure(figsize=(12, 6))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.title('Word Cloud: Skill yang Paling Sering Muncul', fontsize=16, fontweight='bold')
st.pyplot(fig)
